name: 'sbert_retrieval'
platform: 'pytorch_libtorch'
max_batch_size: 4
input [
    {
        name: 'sbert_input_ids',
        data_type: TYPE_INT64,
        dims: [-1]
    },
    {
        name: 'sbert_attention_mask',
        data_type: TYPE_INT64,
        dims: [-1]
    },
    {
        name: 'sbert_token_type_ids',
        data_type: TYPE_INT64,
        dims: [-1]
    },
    {
        name: 'bm25_index_selection',
        data_type: TYPE_INT64,
        dims: [-1]
    },
    {
        name: 'top_k_sbert',
        data_type: TYPE_INT64,
        dims: [1]
    },
    {
        name: 'bm25_scores',
        data_type: TYPE_FP32,
        dims: [-1]
    },
]
output [
    {
        name: 'sbert_index_selection',
        data_type: TYPE_INT64,
        dims: [-1]
    }
]

output [
    {
        name: 'retrieval_scores',
        data_type: TYPE_FP32,
        dims: [-1]
    }
]

instance_group [
    { 
        kind: KIND_CPU
    }
]