name: 'ensemble_model'
platform: 'ensemble'
max_batch_size: 4

input: [
    {
        name: 'query',
        data_type: TYPE_STRING,
        dims: [1]
    }
]

output [
    {   
    name: "e2e_answer"
    data_type: TYPE_STRING
    dims: [-1]
  }
]



ensemble_scheduling{
    step [
        {
            model_name: 'bm25_retrieval',
            model_version: -1,
            input_map {
                key: 'question',
                value: 'query'
            },
            output_map {
                key: 'index_selection',
                value: 'ml_index_selection'
            },
            output_map {
                key: 'sentence_bert_input_ids',
                value: 'sbert_ids'
            },
            output_map {
                key: 'sentence_bert_attention_mask',
                value: 'sbert_mask'
            },
            output_map {
                key: 'sentence_bert_token_type_ids',
                value: 'sbert_token_ids'
            },
            output_map {
                key: 'top_k',
                value: 'top_k_selection'
            },
            output_map {
                key: 'bm25_scoring',
                value: 'bm25_score_value'
            }
        },
        {
            model_name: 'sbert_retrieval',
            model_version: -1,
            input_map {
                key: 'sbert_input_ids',
                value: 'sbert_ids'
            },
            input_map {
                key: 'sbert_attention_mask',
                value: 'sbert_mask'
            },
            input_map {
                key: 'sbert_token_type_ids',
                value: 'sbert_token_ids'
            },
            input_map {
                key: 'bm25_index_selection',
                value: 'ml_index_selection'
            },
            input_map {
                key: 'top_k_sbert',
                value: 'top_k_selection'
            },
            input_map {
                key: 'bm25_scores',
                value: 'bm25_score_value'
            },
            output_map {
                key: 'sbert_index_selection',
                value: 'final_retrieval_stage_selection'
            }
        },
        {
            model_name: 'qa_input',
            model_version: -1,
            input_map {
                key: 'qa_document_indexs',
                value: 'final_retrieval_stage_selection'
            },
            input_map {
                key: 'query_user',
                value: 'query'
            },
            output_map {
                key: 'input_ids',
                value: 'qa_input_ids'
            },
            output_map {
                key: 'attention_mask',
                value: 'qa_attention_mask'
            },
            output_map {
                key: 'align_matrix',
                value: 'qa_align_matrix'
            }
        },
        {
            model_name: 'qa_model',
            model_version: -1,
            input_map {
                key: 'mrc_input_ids',
                value: 'qa_input_ids'
            },
            input_map {
                key: 'mrc_input_mask',
                value: 'qa_attention_mask'
            },
            input_map {
                key: 'mrc_input_align_matrix',
                value: 'qa_align_matrix'
            },
            output_map {
                key: 'start_logits',
                value: 'mrc_start_logits'
            },
            output_map {
                key: 'end_logits',
                value: 'mrc_end_logits'
            },
            output_map {
                key: 'input_ids',
                value: 'mrc_input_ids'
            },
            output_map {
                key: 'align_matrix',
                value: 'mrc_align_matrix'
            },
        },
        {
            model_name: 'qa_postprocess',
            model_version: -1,
            input_map {
                key: 'e2e_start_logits',
                value: 'mrc_start_logits'
            },
            input_map {
                key: 'e2e_end_logits',
                value: 'mrc_end_logits'
            },
            input_map {
                key: 'e2e_input_ids',
                value: 'mrc_input_ids'
            },
            input_map {
                key: 'e2e_align_matrix',
                value: 'mrc_align_matrix'
            },
            output_map {
                key: 'answer',
                value: 'e2e_answer'
            },
        }
    ]
}