name: 'bm25_retrieval'
backend: 'python'
max_batch_size: 4
input: [
    {
        name: 'question',
        data_type: TYPE_STRING,
        dims: [1]
    }
]
output [
    {
        name: 'bm25_index_selection',
        data_type: TYPE_INT32,
        dims: [-1]
    }
]
output [
    {
        name: 'sbert_input_ids',
        data_type: TYPE_INT64,
        dims: [-1]
    }
]
output [
    {
        name: 'sbert_attention_mask',
        data_type: TYPE_INT64,
        dims: [-1]
    }
]
output [
    {
        name: 'sbert_token_type_ids',
        data_type: TYPE_INT64,
        dims: [-1]
    }
]
output [
    {
        name: 'top_k_sbert',
        data_type: TYPE_INT64,
        dims: [1]
    }
]

instance_group [{ kind: KIND_CPU }]

parameters: [
     {
	key: "EXECUTION_ENV_PATH",
        value: {string_value: "model/dev.tar.gz"}
     },
     {
        key: 'path_corpus',
        value: {
            string_value: "model/corpus.json"
        }
    },
    {
        key: 'top_k_bm25',
        value: {
            string_value: '10'
        }
    },
    {
        key: 'top_k_sbert',
        value: {
            string_value: '3'
        }
    }
]
