name: 'bm25_retrieval'
backend: 'python'
max_batch_size: 4
input: [
    {
        name: 'question',
        data_type: TYPE_STRING,
        dims: [-1]
    }
]
output [
    {
        name: 'bm25_index_selection',
        data_type: TYPE_INT32,
        dims: [-1]
    }
]

instance_group [{ kind: KIND_CPU }]

parameters: [
    {
        key: 'path_corpus',
        value: {
            string_value: "/model/bm25_retrieval/corpus.json"
        }
    },
    {
        key: 'top_k',
        value: {
            string_value: '5'
        }
    }
]