name: 'bm25_retrieval'
backend: 'python'
max_batch_size: 4
input: [
    {
        name: 'question',
        data_type: TYPE_STRING,
        dims: [1]
    }
]
output [
    {
        name: 'index_selection',
        data_type: TYPE_INT64,
        dims: [-1]
    }
]


instance_group [
    { 
        kind: KIND_GPU 
    }
]

parameters: [
     {
	    key: "EXECUTION_ENV_PATH",
        value: {string_value: "model/dev.tar.gz"}
     },
     {
        key: 'path_corpus',
        value: {
            string_value: "model/corpus.json"
        }
    },
    {
        key: 'path_config',
        value: {
            string_value: "model/train_qa.yaml"
        }
    },
    {
        key: 'top_k_bm25',
        value: {
            string_value: '15'
        }
    },
    {
        key: 'top_k_sbert',
        value: {
            string_value: '3'
        }
    }
]
