name: "qa_model"
platform: "pytorch_libtorch"
max_batch_size: 4
input [
 {
    name: "mrc_input_ids"
    data_type: TYPE_INT64
    dims: [-1]
  } ,
{
    name: "mrc_input_mask"
    data_type: TYPE_INT64
    dims: [-1]
  } ,
{
    name: "mrc_input_align_matrix"
    data_type: TYPE_FP32
    dims: [-1, -1]
  }
]
output [
    {   
    name: "start_logits"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

output [
  {   
    name: "end_logits"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

output [
  {   
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [-1]
  }
]


output [
  {   
    name: "align_matrix"
    data_type: TYPE_FP32
    dims: [-1, -1]
  }
]

instance_group [
    { 
        kind: KIND_GPU
    }
]
